/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHanumanWaterToken,
  IHanumanWaterTokenInterface,
} from "../../../contracts/HanumanWaterTokenPresale.sol/IHanumanWaterToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mintPresaleTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IHanumanWaterToken__factory {
  static readonly abi = _abi;
  static createInterface(): IHanumanWaterTokenInterface {
    return new Interface(_abi) as IHanumanWaterTokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHanumanWaterToken {
    return new Contract(address, _abi, runner) as unknown as IHanumanWaterToken;
  }
}
