/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { HanumanWaterTokenPresale__factory } from "./HanumanWaterTokenPresale__factory";
export { IHanumanWaterToken__factory } from "./IHanumanWaterToken__factory";
