/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HWTPresale } from "./HWTPresale";
export type { HanumanWaterToken } from "./HanumanWaterToken";
