/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as hanumanWaterTokenPresaleSol from "./HanumanWaterTokenPresale.sol";
export type { hanumanWaterTokenPresaleSol };
import type * as mocks from "./mocks";
export type { mocks };
export type { HWTPresale } from "./HWTPresale";
export type { HanumanWaterToken } from "./HanumanWaterToken";
export type { HanumanWaterTokenV2 } from "./HanumanWaterTokenV2";
