/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HanumanWaterTokenPresale } from "./HanumanWaterTokenPresale";
export type { IHanumanWaterToken } from "./IHanumanWaterToken";
