/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as hanumanWaterTokenPresaleSol from "./HanumanWaterTokenPresale.sol";
export * as mocks from "./mocks";
export { HWTPresale__factory } from "./HWTPresale__factory";
export { HanumanWaterToken__factory } from "./HanumanWaterToken__factory";
export { HanumanWaterTokenV2__factory } from "./HanumanWaterTokenV2__factory";
